# Generated by Django 3.0.2 on 2020-12-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_allbid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllBid',
            new_name='AllBids',
        ),
    ]
