# Generated by Django 3.0.2 on 2020-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='in_watchlist',
            field=models.BooleanField(default=True),
        ),
    ]
